name: build-zulu-dictionary-app
on:
  push: {}
  repository_dispatch:
    types: [run]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build using herokuish
        run: |
          cat <<EOF > Dockerfile  
          FROM gliderlabs/herokuish as builder
          COPY . /tmp/app
          ARG BUILDPACK_URL
          ENV USER=herokuishuser
          RUN /bin/herokuish buildpack build
          
          FROM gliderlabs/herokuish
          COPY --chown=herokuishuser:herokuishuser --from=builder /app /app
          ENV PORT=5000
          ENV USER=herokuishuser
          EXPOSE 5000
          CMD ["/bin/herokuish", "procfile", "start", "web"]
          EOF
          docker build --build-arg BUILDPACK_URL="$BUILDPACK_URL" --tag "$GITHUB_REPOSITORY:$GITHUB_REF_NAME" .
          docker images
          