name: Deploy zuludict-app
env:
  DOCKER_TAG: ghcr.io/acdh-oeaw/zuludict-app
on:
  workflow_call: {}
  workflow_dispatch: {}
  repository_dispatch:
    types: [run]
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
      name: Checkout
    - name: Kubernetes credentials
      uses: actions-hub/kubectl@v1.21.2
      env:
        KUBE_CONFIG: ${{ secrets.ACDH_KUBE_CONFIG }}
      with:
        args: config set-context --current --namespace=zuludict-app
    - name: Deploy using helm and the local helm chart
      run: |
        helm upgrade zuludict-app .github/auto-deplay-app --values .github/auto-deploy-app-values.yaml --install --atomic